"""add session ttl hours to site settings

Revision ID: a71b391b1047
Revises: 0017_import_archive_sha256
Create Date: 2026-08-13 02:24:41.610368+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a71b391b1047'
down_revision: str | None = '0017_import_archive_sha256'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'content_format',
               existing_type=sa.VARCHAR(length=16),
               server_default='html',
               existing_nullable=False)
    op.add_column('site_settings', sa.Column('session_ttl_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'session_ttl_hours')
    op.alter_column('pages', 'content_format',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
